### ISSUE TITLE
After upgdate into 5.0 it generates Object objects instead of Array of objects

### ISSUE THREAD

**Issue by chompomonim** [Meteor-Community-Packages/meteor-autoform#770] opened 2015-03-14 18:29 UTC
Schema:

``` coffeescript
  loyalty_cards:
    label: "Loyalty cards"
    type: Array
    optional: true
  'loyalty_cards.$':
    type: Object
    optional: true
  'loyalty_cards.$.name':
    type: String
    optional: true
  'loyalty_cards.$.number':
    label: "Card number"
    type: String
    optional: true
```

Result:

```
loyalty_cards:  Object
  0: Object
  1: Object
```

Now I can't use {{#each loyalty_cards}}, I'm getting: 

```
Exception from Tracker recompute function: Error: {{#each}} currently only accepts arrays, cursors or falsey values.
    at badSequenceError (http://localhost:3000/packages/observe-sequence.js?2fd807ea171ead273b9e6458607cb226012d9240:179:10)
    at http://localhost:3000/packages/observe-sequence.js?2fd807ea171ead273b9e6458607cb226012d9240:144:17
    at Object.Tracker.nonreactive (http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:513:12)
    at http://localhost:3000/packages/observe-sequence.js?2fd807ea171ead273b9e6458607cb226012d9240:121:15
    at Tracker.Computation._compute (http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:296:36)
    at Tracker.Computation._recompute (http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:310:14)
    at Tracker.flush (http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:440:14)
```

**Comment by elGusto** [comment] 2015-03-16 13:31
Shouldn't it be like this then ? 
```coffeescript
    loyalty_cards:
       label: "Loyalty cards"
       type: [Object] # Instead of Array
       optional: true
    'loyalty_cards.$':
      type: Object
      optional: true
    'loyalty_cards.$.name':
      type: String
      optional: true
    'loyalty_cards.$.number':
      label: "Card number"
      type: String
      optional: true
```

**Comment by aldeed** [comment] 2015-03-16 17:13
Is this a duplicate of https://github.com/aldeed/meteor-autoform/issues/765? Mongo issue

**Comment by chompomonim** [comment] 2015-03-17 12:05
@aldeed Yes, #765 sound like same issue. However there are no solution for it in that task and task is already closed :( 

So, what should I do to avoid errors while using `{{#each loyalty_cards}}`? 

For now I have to have template which converts from Object of Objects into Array of Objects.

```CoffeeScript
  cards: ->
    # Transform loyalty_cards Object of Objects into Array of Objects
    cards = Clients.findOne(@_id).loyalty_cards
    $.map cards, (value, index) -> [value]
```

**Comment by aldeed** [comment] 2015-03-17 13:13
I reopened the other issue to track. Can you post your full form, helpers, etc.? I'm not sure if this is the same issue. My point was that if you end up with an object instead of an array when you insert, then it's probably because you need to pre-create the empty array in mongo. But assuming the data is stored correctly, then {{#each}} should work fine.

**Comment by harryhurry** [comment] 2015-03-21 19:48
Just to mention, I have the same issue since upgrading to 5.0, also valid for 5.0.3. Getting the same error.  
Part of my Schema:
<pre>
...
bankAccounts: {
    type: Array,
    label: 'Bankverbindungen',
    optional: true
  },
  'bankAccounts.$': {
    type: Object,
    optional: true
  },
  'bankAccounts.$.bankAccount': {
    type: Schemas.BankAccountType,
    label: 'Bankverbindung',
    optional: true
  },
...
</pre>

Taking out the "optional: true" doesn't change anything.

In the previous version of autoform the following was working, too, which now doesn't work either:
<pre>
...
bankAccounts: {
    type: [Object],
    label: 'Bankverbindungen',
    optional: true
  },
  'bankAccounts.$': {
    type: Object,
    optional: true
  },
  'bankAccounts.$.bankAccount': {
    type: Schemas.BankAccountType,
    label: 'Bankverbindung',
    optional: true
  },
...
</pre>

Would be great if this issue could get solved soon to avoid temporary workarounds.

b.t.w.; Autoform is cool!

**Comment by chompomonim** [comment] 2015-03-23 13:18
I just tried to create clean project with my collection, but it seems to work well. I'll look on my big project, probably it's relates to some other package, or so.

**Closed** 2021-02-18 08:32 UTC
Labels: needs reproduction, potential bug
