### ISSUE TITLE
Array items don't update properly when you delete an item other than the last one

### ISSUE THREAD

**Issue by rclai** [Meteor-Community-Packages/meteor-autoform#1004] opened 2015-06-04 12:13 UTC
Schema:

``` js
MyCollection.attachSchema(new SimpleSchema({
  qtys: {
    type: [new SimpleSchema({
      qty: {
        type: Number,
        autoform: {
          defaultValue: 1
        }
      }
    })],
    min: 1,
    autoValue: function () {
      if (this.isInsert && ! this.isSet) {
        return [{
          qty: 1
        }];
      }
    },
    custom: function () {
      // Pay attention to the `length` and indexes of `this.value`
      console.log(this.value);
    }
  }
}));
```

Form:

``` handlebars
{{#autoForm id="MyFormId" class="clearfix" collection="MyCollection" type="update" doc=this resetOnSuccess=false}}
  <ul class="list-inline">
    {{#afEachArrayItem name="qtys"}}
      <li>
        {{> afQuickField class="input-sm" name=this.current.qty}}
        <button style="{{#if afArrayFieldIsFirstVisible}}visibility:hidden{{/if}}" class="autoform-remove-item" data-autoform-field="qtys"><span class="glyphicon glyphicon-minus"></span></button>
      </li>
    {{/afEachArrayItem}}
    <li class="qtysItem">
      <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok-circle"></span> Save</button>
      <button class="btn btn-primary autoform-add-item" data-autoform-field="qtys"><span class="glyphicon glyphicon-plus"></span> Add</button>
    </li>
  </ul>
{{/autoForm}}
```

I noticed this when I was debugging a custom validation rule in the simple schema for the `qtys` field. Say I had three items, and I minused out the second item and hit save, it would break. I noticed that the `this.value` value in the custom validator showed an array with the remaining two items, but I noticed that their indexes were `0` and `2`, and the `length` property showed `3`, which was weird. So I had to [`_.compact(this.value)`](http://underscorejs.org/#compact), before I could do any custom validation or it would break on me.

And in order to fix this on the MongoDB operation side, I had to do a `before.update` collection hook where I would do:

``` js
MyCollection.before.update(function (userId, doc, fields, modifier, options) {
  // Do some checks for my desired field.. blah blah..  
  modifier.$set.qtys = _.compact(modifier.$set.qtys);
});
```

Because `modifier.$set.qtys` would be an array of three items, where the second item was a `null` value:

``` js
[
  {
    qty: 1
  },
  null, // here it is
  {
    qty: 3
  }
]
```

**Comment by stachrom** [comment] 2015-06-17 12:56
duplicate of https://github.com/aldeed/meteor-autoform/issues/838

**Comment by stachrom** [comment] 2015-06-17 13:03
duplicate of https://github.com/aldeed/meteor-autoform/issues/914

**Closed** 2021-02-18 08:34 UTC
