### ISSUE TITLE
Remove array fields doesn't update the form

### ISSUE THREAD

**Issue by mazing** [Meteor-Community-Packages/meteor-autoform#1099] opened 2015-07-23 09:53 UTC
If I enable autosave with `{{> quickForm autosave=true ...}}` the form is not updated when objects in an array field are removed.

**Comment by AnthonyAstige** [comment] 2015-09-15 18:45
I'm getting the same thing.  Particularly troublesome in combination with `buttonContent=false` as without anything to click submit there's no intuitive way for the user to save removed array elements.

### Workaround code that's working for me (specific to my collection)

```javascript
// Bandaid for AutoForm not removing array elements, GitBug @ https://goo.gl/SBijNR
'click .autoform-remove-item': function(e) {
    // SO Thread @ https://goo.gl/uY0R2U discussing how to remove specific element
    // * Can't use $unset >> $pull as $pull doesn't seem to work with minimongo
    var set = Sets.findOne(id());
    delete set._id;                     // Minimongo doesn't like to update _id
    set.actions.splice(this.index, 1);  // Get rid of indexed array element
    Sets.update(id(), { $set: set });
}
```

### Background findings
* Same problem on both 5.4.1 and 5.5.0
* There appears to be no network traffic on clicking the minus button to remove an array item
* If I edit another field, the form does save, including removed array items
* I tried simply submitting the form via JavaScript in that same event call, but got odd results

**Comment by gduquesnay** [comment] 2017-01-17 15:16
Had some trouble following @AnthonyAstige 's code above.  Eventually figured it out.  Posting it here in case it helps anyone else out.

```
  'click .autoform-remove-item': (e, tmpl) ->
    ticketNumbers = tmpl.data.remedyTicketNumber
    ticketNumbers.splice(@.index, 1)
    Sessions.update tmpl.data._id, $set: {remedyTicketNumber: ticketNumbers}
```

**Comment by kjrhody** [comment] 2021-01-28 21:44
Commenting to note that I am having the same issue. Thanks for the code, will try and report back if it works.

**Comment by jankapunkt** [comment] 2021-01-30 17:30
@kjrhody this should be fixed in AutoForm 7.0.0, can you provide me an example to reproduce this?

**Comment by kjrhody** [comment] 2021-02-01 12:50
@jankapunkt We are currently using 6.3.0. Is the upgrade to 7.0 intensive? If so, we may not be able to upgrade for quite some time. If we can't upgrade to 7.0, Is there a code snippet or patch you could provide that would fix it in 6.3.0?

The use case example is that we have a survey where each of the steps uses a different form. Each of the forms is set to `autosave=true` and has a custom form hook for the form submit. In the survey when we encounter an array field, we are able to add an item in the UI by clicking the + button. We populate the fields for that item, and they are all inserted into the database. However if we wish to remove that item, we click the minus button next to it. The item will be removed from the array in the UI, however the form will not actually trigger an update and the item will not be removed from the database. Therefore when the page is reloaded, the item persists, since it has not been removed from the db. This is true for all of the array fields in our entire survey.

**Comment by jankapunkt** [comment] 2021-02-01 13:00
@kjrhody the [migration to 7.0.0](https://github.com/Meteor-Community-Packages/meteor-autoform#installation) is well documented and should not take more than 30minutes. Compatibility with extensions can be regarded and troubleshooting is also covered.

A patch for 6.3.0 is possible but will take time (days to weeks), since I first have to see what commit fixed the array reactivity and how far it changed the internals and at the moment I am really busy maintaining our own projects.

Please try the update first and let me know if you get stuck.

**Comment by kjrhody** [comment] 2021-02-01 13:04
@jankapunkt Thanks for your quick response! We will try the upgrade and report back.

**Closed** 2021-02-18 08:35 UTC
