### ISSUE TITLE
Validation errors are not reset when navigated away from the form

### ISSUE THREAD

**Issue by serkandurusoy** [Meteor-Community-Packages/meteor-autoform#1118] opened 2015-08-04 22:03 UTC
Navigating away from a form causes its values to be reset, but not its validations.

To reproduce:
- Create an app with two routes
- One route contains a form with required fields
- Submit the empty form with some fields left empty to see the validation errors
- Navigate away
- Come back to the form to see that all values have been cleared, but the validation errors are still there

I would expect either one of:
- Keep the values as well
- Or clear the validation errors, too

**Comment by FelipeRosa** [comment] 2015-08-08 21:57
+1

**Comment by drnachio** [comment] 2015-09-07 16:10
+1

**Comment by thebarty** [comment] 2015-10-18 23:24
Hi guys,

I just stumbled upon this one.

@serkandurusoy: Is there a way to manually reset autoform-errors, p.e. when leaving the route?

**Comment by serkandurusoy** [comment] 2015-10-19 00:18
I use flow router and place `$('form')[0].reset()` within an exit trigger for all routes that contain forms.

**Comment by thebarty** [comment] 2015-10-20 09:13
@serkandurusoy: 
Oh yeah!!!

I worked around it in Template.onRendered like this:
```
Template.contactsEditForm.onRendered(function () {
  // cleanup autoform (due to bug in autoform see https://github.com/aldeed/meteor-autoform/issues/1118)
  //  needs to be called in ``onRendered`` (it DOES NOT work in ``onCreated``)
  AutoForm.resetForm('daFormID');
 
  //...
```

**Comment by serkandurusoy** [comment] 2015-10-20 10:39
I would advise against it because you might have other errors, messages or prepopulated values that you manually add to your form when it is rendered. So the better way would be to reset it right before you destroy it and an exit trigger works well in that case.

**Comment by thebarty** [comment] 2015-10-20 11:09
The problem is that I got a usecase, where the form is called as a modal. So I am not opening the form via an url, but with a ``Modal.show('theForm');`` .... I tried ``Template.onDestroyed`` but it does not trigger, as the modal is not being destroyed when closing the modal. So I'll guess I should have a ``modal.close()``-trigger and put it there?

By the way... totally different topic, but what's your current take on testing? see here https://forums.meteor.com/t/testing-for-newbies-current-state-what-frameworks-what-tutorials/11765

**Comment by serkandurusoy** [comment] 2015-10-20 11:22
Yep a modal.close() would be a great way to handle it. Furthermore, a more meteor way would be to make a modal template and render it on the fly and then destroy it, you can use the Blaze.render() api for that. Sorry about the testing, I have not yet done much on that front :(

**Comment by nchenbang** [comment] 2015-10-31 10:46
Is this considered as a normal behavior or is it a bug? 

By the way, I was trying to use @serkandurusoy way as a workaround but it ended up that exit trigger in flow router is called after leaving the page, which makes it impossible to reset autoform in an exit trigger (Or I was doing it the wrongly?)

Right now I am using @thebarty solution as a temporary solution but hopefully someone can come up with a better solution for this.

**Comment by serkandurusoy** [comment] 2015-10-31 12:14
Hmm, this is rather peculiar. The exit trigger method works for my app. Now I wonder why it does. Ping @arunoda

**Closed** 2021-02-18 08:35 UTC
