### ISSUE TITLE
afFieldValueIs and AutoForm.getFieldValue not reactive with checkboxes

### ISSUE THREAD

**Issue by erasaur** [Meteor-Community-Packages/meteor-autoform#861] opened 2015-04-06 02:42 UTC
The helper returns true when the checkbox is initially checked, but doesn't return false when the checkbox is subsequently unchecked. Same behavior with `AutoForm.getFieldValue`.

```
<head>
  <title>test-checkbox</title>
</head>

<body>
  {{> hello}}
</body>

<template name="hello">
  {{#autoForm collection="FieldValueIs" type="insert" id="FieldValueIsForm"}}
    {{> afQuickField name="a"}}
    {{#if afFieldValueIs name="a" value=true}}
      {{> afQuickField name="b"}}
    {{/if}}
  {{/autoForm}}
</template>
```

```
FieldValueIs = new Mongo.Collection("FieldValueIs");
FieldValueIs.attachSchema(new SimpleSchema({
  a: {
    type: Boolean
  },
  b: {
    type: String
  }
}));
```

**Comment by marktomm** [comment] 2015-04-11 11:47
Hello!

I have also stumbled upon this buggy behavior in autoform.

The only workaround I have found so far is set a Session variable on click event if I want to dynamically change properties in the schema:

<pre>
//hello.js

Template.hello.events({
  "click #a": function() {
    Session.set('form_a_Option', AutoForm.getFieldValue('a', 'FieldValueIsForm'));
  }
});


//colleciton.js

FieldValueIs = new Mongo.Collection("FieldValueIs");
FieldValueIs.attachSchema(new SimpleSchema({
  a: {
    type: Boolean
  },
  b: {
    type: String,
    autoform: {
      type: function() {
        if(!Session.get('form_a_Option'))
          return "hidden";
          
        return "";
      }
    }
  }
}));
</pre>

or write a custom helper for hello template

<pre>
Template.hello.helpers({
  is_a_OptionYes: function() {
    return AutoForm.getFieldValue('a');
  }
});
</pre>

The examples here assume an id "a" is assigned to the appropriate field i "hello" template:
{{#if afFieldValueIs name="a" id="a" value=true}}

**Comment by abecks** [comment] 2015-04-15 19:06
Confirmed, I'll see if I can diagnose and PR a fix.

**Comment by abecks** [comment] 2015-04-15 20:03
This is fixed in #889, monitor that pull request to see when the package is updated.

**Comment by rclai** [comment] 2015-04-15 20:23
What crazy timing, I created a [reproduction](https://github.com/rclai/autoform-affieldvalueis-issue) just now lol.

**Comment by chompomonim** [comment] 2015-04-26 09:51
Faced with the same problem.
Am I right that we're waiting until @aldeed will accept pull request?

**Comment by sandelld** [comment] 2015-05-05 22:21
ditto - getting the same issue.

**Comment by cskaandorp** [comment] 2015-05-06 12:48
ditto

**Comment by tcastelli** [comment] 2015-05-11 16:00
+1

**Comment by Igor1201** [comment] 2015-05-11 19:02
ditto

**Comment by cskaandorp** [comment] 2015-05-13 10:29
Why is it so awfully quite on this package. I saw a couple of pull requests with bug fixes but nothing is happening. I rely heavily on this package. Is everything ok with Aldeed.... Does anybody know.

**Comment by neoromantic** [comment] 2015-05-16 13:40
Waiting for PR to pull through as well.

**Comment by neoromantic** [comment] 2015-05-16 13:48
> or write a custom helper for hello template
>
> //hello.js
>
> Template.hello.helpers({
>   is_a_OptionYes: function() {
>     return AutoForm.getFieldValue('a');
>   }
> });

This approach doesn't work in a same way template helper doesn't. It triggers just once.

**Comment by aadamsx** [comment] 2015-05-18 23:52
Just felt this bite me too!  Why is there no response on this package to pull requests? -- so many people depend on it now...

**Comment by sculley4** [comment] 2015-05-21 07:10
I have been struggling with this as well. marktomm's  first work around is what I am doing for now, when the form #id is clicked, I set a Session variable with the AutoForm getFieldValue for the boolean, and then use this for a template #if helper. It works, just a little clunky.

**Comment by cskaandorp** [comment] 2015-05-21 08:48
I also have an issue with afFieldValueIs and AutoForm.getFieldValue. Don't know if it is really related to checkboxes. It seems that afFieldValueIs is not picking up the data in an update-form. I am too much of a noob to understand this has something to do with reactivity. Probably. I tried to trace it, for what it is worth, and described the thing in #877. 

Since I have over 200 input fields, a very complicated form and a lot of conditional questions this work-around will cost me more time than downgrading to 4.2.2. So that's what I did. All is fine now.

Apparently Aldeed is busy on his meteor-rest package. I sympathise with the rant in #877. Meteor-autoform is widely used by a lot of people. Right now it has 12 pull requests and nothing significant has been done for a while. I don't completely understand how all of this works. So maybe this is bullshit, but it would sure be nice if more people could help out on this and accept pull requests. It looks like we are waiting for a person who's workload is over level asian.

**Comment by abecks** [comment] 2015-05-26 01:32
I am keeping my fork up to date for now until @aldeed steps back into the ring. I will accept PR's at my fork (https://github.com/abecks/meteor-autoform/) and hopefully merge back when he returns.

**Comment by sakulstra** [comment] 2015-10-28 10:02
:+1:

**Comment by johndevor** [comment] 2016-12-28 17:34
+1

**Closed** 2021-02-18 08:33 UTC
